# -*- coding: utf-8 -*-
"""cropping_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TmrRQEwvMSRdT5hIluThL_zPbSIQZ69_
"""
import matplotlib.pyplot as plt
from PIL import Image
from PIL import ImageOps
import os

# testing crop functionality -----
# crop_folder = '/cropped/'
# im = Image.open('lookCamera_hand.PNG')
# box = (165, 90, 685, 380)
# box_2 = (165, 390, 685, 680)
# box_3 = (700, 695, 1220, 985)
# im_1 = im.crop(box_3)
# im_1.save('cropped/TEST.PNG')
# --------------------------------

directory = '/content/drive/My Drive/ECE324 Project (Fall 2020)/Data'
img_list = []
for filename in os.listdir(directory):
  if filename.endswith(".PNG"):
    img_list.append(os.path.join(filename))

for i in range(len(img_list)):
  img_list[i] = img_list[i][:-4] # removing the file extension ".PNG"

def cropper(img_list):
  for im_dir in img_list:
    im = Image.open(im_dir + '.PNG')
    box = (165, 90, 685, 380)
    for i in range(3):
      im_crop = im.crop(box)
      im_crop.save('cropped/' + im_dir + str(i+1) + '.PNG')

      box_list = list(box)
      box_list[0] += 535
      box_list[2] += 535
      box = tuple(box_list)
    
    box_2 = (165, 390, 685, 680)
    for i in range(3,6):
      im_crop = im.crop(box_2)
      im_crop.save('cropped/' + im_dir + str(i+1) + '.PNG')

      box_list = list(box_2)
      box_list[0] += 535
      box_list[2] += 535
      box_2 = tuple(box_list)
    
    box_3 = (700, 695, 1220, 985)
    im_crop = im.crop(box_3)
    im_crop.save('cropped/' + im_dir + '7.PNG')

cropper(img_list)
